### ISSUE TITLE
Connection without password fails

### ISSUE THREAD

**Issue by NathanReb** [arenadotio/pgx#42]
I'm trying to connect with a user that has no password (ie password set to `null`) and it raises an `End_of_file` exception.

I set `verbose` to `2` to get a little more detail on this and obtained the following logs:
```
FATAL: 28P01: password authentication failed for user "nathan"
R: auth_failed
L: 328
F: auth.c
V: FATAL
```

From a quick look at the code and the [postgres documentation](https://www.postgresql.org/docs/11/static/auth-password.html) it looks to me like it may attempt to perform password auth when it shouldn't.

Do you have any idea what might be going wrong here ?

I'm happy to provide more logs/info to help figuring this out as well as a patch if it is indeed a bug.

**Comment by brendanlong** [comment]
I've only looked at this for a short time, but it looks like Pgx only tries to send a password if it's requested by the database. There is a somewhat-confusing behavior where instead of failing with no password, we automatically set the password to `""` (also, we lookup passwords in the `PGPASSWORD` environment variable).

Does it change anything if you `unset PGPASSWORD`?

If you want to try to debug this / write a patch, the relevant code is in pgx/src/pgx.ml, the function `connect` on line 887. (This function has some whitespace in it, so the code continues down to line 1008)

**Comment by NathanReb** [comment]
Ok so I dug a bit more into this and found out that it's unrelatded to `pgx`.

I was trying to connect via TCP on `localhost` rather than using unix sockets and it turns out postgres default configuration is to ask for md5 password authentication on TCP connections thus making it impossible to connect with a user that has no password set.

I tried to set `unix_domain_socket_dir` to the right directory instead and it worked like a charm!

I don't think there's anything to do here on the `pgx` side except maybe a bit of documentation for the complete beginners such as myself.

Feel free to close this issue!

Thanks!

**Comment by brendanlong** [comment]
Thanks for the info! I think people should see this issue if they search for Pgx login problems now :)
